### PR TITLE
UI - hosts/strata, permit dash payment due issue

### PR DESCRIPTION
**Pull request by kialj876**
*Issue:*

- bcgov/entity/issues/24947
- bcgov/entity/issues/24943

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the namex license (Apache 2.0).

### CODE REVIEW

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://strr-strata-hotel-dev--pr-393-huzzbhdo.web.app

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://strr-hosts-dev--pr-393-5ftr9wjf.web.app

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://strr-strata-hotel-dev--pr-393-huzzbhdo.web.app

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://strr-hosts-dev--pr-393-5ftr9wjf.web.app

**Review by deetz99 — APPROVED** [review]
Looks good 👍

**Pull request merged**
