### PR TITLE
Account Flow Fixes. Remove New Tabs. Redirects.

### PR DESCRIPTION
**Pull request by dimak1**
*Issue:*

- bcgov/entity/issues/23663
- bcgov/entity/issues/24175
- bcgov/entity/issues/22830

*Description of changes:*
- Update Account Flow to remove localStorage and bring back sessionStorage.
- Remove opening buttons/links in a new tab
- Redirect Hosts and Examiners to their Dashboards
- For non-existing URLs redirect user to the Dashboard

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the namex license (Apache 2.0).

### CODE REVIEW

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://strr-ui-dev--pr-255-wp3n9hpg.web.app

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://strr-ui-dev--pr-255-wp3n9hpg.web.app

**Comment by rstens** [comment]
First connected with BCSC - Sent to create account - This was correct
Then logout and login (same browser) with IDIR and sent to account-create - not correct.

**Comment by shaangill025** [comment]
@rstens What BCSC account are you using?

**Comment by dimak1** [comment]
@rstens can you pls send me account(s) credentials in the chat, I will try to reproduce, thanks!

**Comment by rstens** [comment]
> @rstens can you pls send me account(s) credentials in the chat, I will try to reproduce, thanks!

Started wit BCSC 26, then IDIR, then 39

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://strr-ui-dev--pr-255-wp3n9hpg.web.app

**Review by rstens — CHANGES_REQUESTED** [review]
Logging in with IDIR (with no earlier sessions) goes to the root url and not the registry-dashboard. Should be IDR LOGIN -> registry-dashboard not \

**Comment by dimak1** [comment]
@rstens fixed and added redirect from root to Dashboard

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://strr-ui-dev--pr-255-wp3n9hpg.web.app

**Review by rstens — APPROVED** [review]

**Pull request merged**
