### PR TITLE
Add Business Lic Exp Date to Details pages

### PR DESCRIPTION
**Pull request by dimak1**
*Issue:*

- bcgov/entity/issues/23551

*Description of changes:*
- Add Business Lic Exp Date to Application and Registration Details pages

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the namex license (Apache 2.0).

### CODE REVIEW

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://strr-ui-dev--pr-196-y0i1282r.web.app

**Review by shaangill025 — APPROVED** [review]
LGTM

**Review by rstens — CHANGES_REQUESTED** [review]
registry details looks like: 
image

Application details-details looks like:
image

I like the first one more, the second is out of balance. Eithet way, it should be consistent

**Comment by dimak1** [comment]
@rstens I showed to @andyyanggov and he approved it, because there are more fields/changes coming to this section.

**Review by rstens — APPROVED** [review]

**Pull request merged**
