### PR TITLE
Update Account Flow

### PR DESCRIPTION
**Pull request by dimak1**
*Issue:*

- bcgov/entity/issues/23663

*Description of changes:*
- Do not show ToS for IDIR users
- Fixes and state cleanup

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the namex license (Apache 2.0).

### CODE REVIEW

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://strr-ui-dev--pr-236-h87brexm.web.app

**Review by rstens — APPROVED** [review]
LGTM, tested throughout the application for the occurrence of TOS. For IDIR it is gone now.

**Comment by rstens** [comment]
I also accepted one issue in SonarCloud.

**Review by shaangill025 — APPROVED** [review]
LGTM

**Pull request merged**
