### PR TITLE
Support Individual Property Managers for Examiners

### PR DESCRIPTION
**Pull request by dimak1**
*Issue:*

Support Individual Property Managers for Examiners after API changes

*Description of changes:*

#### Application Details pages

Screenshot 2024-12-09 at 14 58 45

Screenshot 2024-12-09 at 14 51 43

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the namex license (Apache 2.0).

### CODE REVIEW

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://strr-ui-dev--pr-366-06wabm58.web.app

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://strr-ui-dev--pr-366-06wabm58.web.app

**Review by thorwolpert — APPROVED** [review]
looks like it covers the change.
nice

**Pull request merged**
