### PR TITLE
Update handling of Terms of Service

### PR DESCRIPTION
**Pull request by dimak1**
*Issue:*

- bcgov/entity/issues/23100

*Description of changes:*
- Update handling of Terms of Service
- Add new middleware and composable

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the namex license (Apache 2.0).

### CODE REVIEW

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://strr-ui-dev--pr-141-sjh9ibfs.web.app

**Review by shaangill025 — APPROVED** [review]

**Review by rstens — APPROVED** [review]
Looks like a pretty comprehensive overhaul, I had some difficulty understanding what changed but I got it. I did some testing and it works the same as when I touched last time.

**Comment by dimak1** [comment]
@rstens I had to make sure the user gets redirected from any page to the ToS, and eliminate extra API calls, etc. and as I worked through it, I had to improve from what it was before.

**Pull request merged**
