### PR TITLE
Update Issue Certificate Endpoint

### PR DESCRIPTION
**Pull request by dimak1**
*Issue:*

- bcgov/entity/issues/23389

*Description of changes:*
- Update Issue Certificate Endpoint

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the namex license (Apache 2.0).

### CODE REVIEW

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://strr-ui-dev--pr-148-thdefwey.web.app

**Comment by shaangill025** [comment]
@dimak1 https://strr-ui-dev--pr-148-thdefwey.web.app/application-details/76 is failing. https://strr-ui-dev.web.app/application-details/76 is working.

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://strr-ui-dev--pr-148-thdefwey.web.app

**Comment by dimak1** [comment]
@shaangill025 should be working now

**Review by shaangill025 — APPROVED** [review]

**Comment by rstens** [comment]
> @dimak1 https://strr-ui-dev--pr-148-thdefwey.web.app/application-details/76 is failing [errors out]. https://strr-ui-dev.web.app/application-details/76 is working.

Actually All fine now.

**Review by rstens — APPROVED** [review]

**Pull request merged**
