### PR TITLE
UI - Platform Application Footer

### PR DESCRIPTION
**Pull request by shaangill025**
*Issue:*

- https://github.com/bcgov/entity/issues/22801

*Description of changes:*
@dimak1 This implements the `BcrosStepperFooter` for platform-application

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the namex license (Apache 2.0).

### CODE REVIEW

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://strr-ui-dev--pr-134-xt7zbx3j.web.app

**Comment by dimak1** [comment]
Hi @shaangill025, since we paused development of the Platform Application, why did we end up finishing the footer for it?

**Comment by shaangill025** [comment]
> Hi @shaangill025, since we paused development of the Platform Application, why did we end up finishing the footer for it?

This work was already done before that I just didn't check it in.

**Review by dimak1 — APPROVED** [review]
Looks good.

**Pull request merged**
