### PR TITLE
Add Loading Indicator. Optimize API calls.

### PR DESCRIPTION
**Pull request by dimak1**
*Issue:*

- bcgov/entity/issues/22518

*Description of changes:*
- Add loading indicator when navigating between pages
- Optimize API calls by combining and calling them at once
- Add icons as a dependency (instead of dev dependency) - an attempt to solve issue when icons not loading

Screenshot 2024-10-08 at 09 59 23

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the namex license (Apache 2.0).

### CODE REVIEW

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://strr-ui-dev--pr-170-sefmeju5.web.app

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://strr-ui-dev--pr-170-sefmeju5.web.app

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://strr-ui-dev--pr-170-sefmeju5.web.app

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://strr-ui-dev--pr-170-sefmeju5.web.app

**Review by shaangill025 — APPROVED** [review]
LGTM

**Pull request merged**
