### PR TITLE
All - UI: New core layer update

### PR DESCRIPTION
**Pull request by deetz99**
*Issue:*

- bcgov/entity/issues/24954

*Description of changes:*
- fix core layer to handle 401 error in auth api plugin
- move handful of common things to connect layer and update all apps to use new version

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the namex license (Apache 2.0).

### CODE REVIEW

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://strr-platform-dev--pr-401-cxwhrtp1.web.app

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://strr-strata-hotel-dev--pr-401-x1hdd1ge.web.app

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://strr-hosts-dev--pr-401-2ldcaixh.web.app

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://strr-platform-dev--pr-401-cxwhrtp1.web.app

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://strr-hosts-dev--pr-401-2ldcaixh.web.app

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://strr-strata-hotel-dev--pr-401-x1hdd1ge.web.app

**Review by thorwolpert — APPROVED** [review]

**Review by dimak1 — APPROVED** [review]
Nice cleanup. LG!

**Pull request merged**
