### PR TITLE
Add Breadcrumb Across the App

### PR DESCRIPTION
**Pull request by dimak1**
*Issue:*

- bcgov/entity/issues/22557

*Description of changes:*
- Add Breadcrumb across the application
- Do not show Breadcrumb on certain routes

Screenshot 2024-09-12 at 11 55 05

Screenshot 2024-09-12 at 11 55 28

Screenshot 2024-09-12 at 11 58 59

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the namex license (Apache 2.0).

### CODE REVIEW

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://strr-ui-dev--pr-139-ql7kgwt5.web.app

**Review by rstens — COMMENTED** [review]
Showing breadcrumb : "My STR Registry Dashboard" for and IDIR login is not correct.

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://strr-ui-dev--pr-139-ql7kgwt5.web.app

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://strr-ui-dev--pr-139-ql7kgwt5.web.app

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://strr-ui-dev--pr-139-ql7kgwt5.web.app

**Review by rstens — CHANGES_REQUESTED** [review]
Please review new SonarCloud issue and accept it if you do not need to change.

**Comment by shaangill025** [comment]
image
image

I believe the application# label is not displaying correctly.

**Comment by dimak1** [comment]
@rstens fixed sonarcloud suggested issues

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://strr-ui-dev--pr-139-ql7kgwt5.web.app

**Review by rstens — APPROVED** [review]

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://strr-ui-dev--pr-139-ql7kgwt5.web.app

**Review by shaangill025 — APPROVED** [review]

**Pull request merged**
