### PR TITLE
Improve Page Loading

### PR DESCRIPTION
**Pull request by dimak1**
*Issue:*

- bcgov/entity/issues/22973

*Description of changes:*
-  Optimize API calls and session storage to speed up page loading

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the namex license (Apache 2.0).

### CODE REVIEW

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://strr-ui-dev--pr-114-u6bqk57h.web.app

**Review by rstens — APPROVED** [review]
Looks good, except for the first time you got to the main url, a very lengthy wait. That might be just the nature of the beast.

**Comment by rstens** [comment]
BTW, if the SonarCloud issue reported is a non issue, you can label it as such by setting the status form "Open" to "Accepted". That way we won't see it reported again.

**Comment by dimak1** [comment]
> Looks good, except for the first time you got to the main url, a very lengthy wait. That might be just the nature of the beast.

@rstens yes, the first time it needs all the data (to be stored in session), so it will be slower a bit. Once we have loading indicator , spinner, it will look better for the user.

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://strr-ui-dev--pr-114-u6bqk57h.web.app

**Pull request merged**
