### PR TITLE
UI - Examiner Dashboard - PropertyManager Application Type Fix

### PR DESCRIPTION
**Pull request by shaangill025**
*Issue:*

- https://github.com/bcgov/entity/issues/23532

*Description of changes:*
image
image
image

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the namex license (Apache 2.0).

### CODE REVIEW

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://strr-ui-dev--pr-288-3chfkxbz.web.app

**Review by dimak1 — APPROVED** [review]
LG

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://strr-ui-dev--pr-288-3chfkxbz.web.app

**Pull request merged**
