### PR TITLE
Application & Registration Details pages. Filing History component. Approve & Reject Application.

### PR DESCRIPTION
**Pull request by dimak1**
*Issue:*

- bcgov/entity/issues/22630
- bcgov/entity/issues/22633

*Description of changes:*
- Application & Registration Details pages. API integration.
- Filing history component
- Integrate new endpoints: Approve & Reject and Application as Examiner

Screenshot 2024-08-15 at 12 46 24

Screenshot 2024-08-16 at 12 42 58

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the namex license (Apache 2.0).

### CODE REVIEW

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://strr-ui-dev--pr-99-7ylu0oqw.web.app

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://strr-ui-dev--pr-99-7ylu0oqw.web.app

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://strr-ui-dev--pr-99-7ylu0oqw.web.app

**Review by shaangill025 — APPROVED** [review]

**Pull request merged**
