### PR TITLE
Add 'max-width' for All Pages

### PR DESCRIPTION
**Pull request by dimak1**
*Issue:*
- bcgov/entity/issues/22484

*Description of changes:*
- Add max-width layout and other small fixes

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the namex license (Apache 2.0).

### CODE REVIEW

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://strr-ui-dev--pr-77-zixs5bn1.web.app

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://strr-ui-dev--pr-77-zixs5bn1.web.app

**Review by shaangill025 — APPROVED** [review]

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://strr-ui-dev--pr-77-zixs5bn1.web.app

**Pull request merged**
