### PR TITLE
Fix Account Flow for Host

### PR DESCRIPTION
**Pull request by dimak1**
*Issue:*

- bcgov/entity/issues/23663
- bcgov/entity/issues/23691

*Description of changes:*
- Update account flow to fix issues
- Fix label for middle name

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the namex license (Apache 2.0).

### CODE REVIEW

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://strr-ui-dev--pr-290-21m5056w.web.app

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://strr-ui-dev--pr-290-21m5056w.web.app

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://strr-ui-dev--pr-290-21m5056w.web.app

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://strr-ui-dev--pr-290-21m5056w.web.app

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://strr-ui-dev--pr-290-21m5056w.web.app

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://strr-ui-dev--pr-290-21m5056w.web.app

**Review by rstens — APPROVED** [review]
Looking good. Bounced back and forth between Host And IDIR a few times, with different starting points. All went as expected.

**Comment by rstens** [comment]
The first name not mandatory issue needs to be discussed.

**Pull request merged**
