### PR TITLE
Host and Examiner Actions in Application

### PR DESCRIPTION
**Pull request by dimak1**
*Issue:*

- bcgov/entity/issues/22937

*Description of changes:*
- Use `hostActions` and `examinerActions` returned by API to display action buttons in the Application

Screenshot 2024-10-11 at 10 01 27

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the namex license (Apache 2.0).

### CODE REVIEW

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://strr-ui-dev--pr-175-4lrlc8r2.web.app

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://strr-ui-dev--pr-175-4lrlc8r2.web.app

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://strr-ui-dev--pr-175-4lrlc8r2.web.app

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://strr-ui-dev--pr-175-4lrlc8r2.web.app

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://strr-ui-dev--pr-175-4lrlc8r2.web.app

**Review by shaangill025 — APPROVED** [review]
LGTM

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://strr-ui-dev--pr-175-4lrlc8r2.web.app

**Pull request merged**
