### PR TITLE
Host UI - Application Submit Button - Loading Animation

### PR DESCRIPTION
**Pull request by shaangill025**
*Issue:*

- https://github.com/bcgov/entity/issues/23658

*Description of changes:*
Fixes issue with applications being submitted multiple times.

## Desktop
image
image

## Mobile
image
image

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the namex license (Apache 2.0).

### CODE REVIEW

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://strr-ui-dev--pr-251-u0zpa1gr.web.app

**Review by dimak1 — APPROVED** [review]
LGTM, thanks for the tests!

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://strr-ui-dev--pr-251-u0zpa1gr.web.app

**Pull request merged**
