### PR TITLE
Add Modal for Account Setup Help

### PR DESCRIPTION
**Pull request by dimak1**
*Issue:*

- bcgov/entity/issues/23018

*Description of changes:*
- Initial setup for Info Modal
- Bcros Contact Info component
- Unit tests
- Cleanup

### App Screenshots 

Screenshot 2024-09-20 at 09 57 10

Screenshot 2024-09-20 at 09 59 10

Screenshot 2024-09-20 at 09 59 20

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the namex license (Apache 2.0).

### CODE REVIEW

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://strr-ui-dev--pr-147-4ak7au9f.web.app

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://strr-ui-dev--pr-147-4ak7au9f.web.app

**Comment by shaangill025** [comment]
I tried it in incognito window and seeing the following issues [missing icons, compared to screenshots in description]
image
image
image

**Comment by dimak1** [comment]
@shaangill025 this is a known issue, the icons are not loading in preview mode (you can see that account menu dropdown doesn't load the icons either). In Dev, the icons are showing up correctly.

**Pull request merged**
