### PR TITLE
Strata/Host - UI: Strata learn more url

### PR DESCRIPTION
**Pull request by deetz99**
*Issue:*

- bcgov/entity/issues/

*Description of changes:*
- add missing strata doc learn more url in nuxt config
- add document types to base layer to be used by strata and host
- add document type to registration response

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the BC Registry and Digital Services BSD 3-Clause License

### CODE REVIEW

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://strr-strata-hotel-dev--pr-421-bu8eszjk.web.app

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://strr-hosts-dev--pr-421-mwr52swz.web.app

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://strr-strata-hotel-dev--pr-421-bu8eszjk.web.app

**Review by thorwolpert — APPROVED** [review]

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://strr-hosts-dev--pr-421-mwr52swz.web.app

**Pull request merged**
