### PR TITLE
Webui local dev - docker compose changes

### PR DESCRIPTION
**Pull request by turb0c0w**
Issue:
- bcgov/entity#22528

Ensure environment variables are available for nuxt at build time in dev container

### CODE REVIEW

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://strr-ui-dev--pr-76-u1z5wxia.web.app

**Review by dimak1 — APPROVED** [review]
Thanks for making the updates.

**Review by rstens — APPROVED** [review]
Ran code locally built correctly and is now functional.

**Pull request merged**
