### PR TITLE
UI - Host Application Stepper Bug Fix & Apply Validation on Submission

### PR DESCRIPTION
**Pull request by shaangill025**
*Issue:*

- https://github.com/bcgov/entity/issues/23039

*Description of changes:*
Includes:
- Fixes the stepper bug as described in the issue
- Prevent submit button action if there is incomplete data or errors. Basically current validation is being applied and enforced.
- ~~`BcrosStepperFooter` for platform-application~~

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the namex license (Apache 2.0).

### CODE REVIEW

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://strr-ui-dev--pr-133-jefo3fb4.web.app

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://strr-ui-dev--pr-133-jefo3fb4.web.app

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://strr-ui-dev--pr-133-jefo3fb4.web.app

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://strr-ui-dev--pr-133-jefo3fb4.web.app

**Review by dimak1 — APPROVED** [review]

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://strr-ui-dev--pr-133-jefo3fb4.web.app

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://strr-ui-dev--pr-133-jefo3fb4.web.app

**Pull request merged**
