### PR TITLE
UI - Display Correct Ownership Type Label

### PR DESCRIPTION
**Pull request by shaangill025**
*Issue:*

- https://github.com/bcgov/entity/issues/22935

*Description of changes:*
Display correct ownership type label in review and application detail.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the namex license (Apache 2.0).

### CODE REVIEW

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://strr-ui-dev--pr-135-z1swt59e.web.app

**Review by dimak1 — COMMENTED** [review]
Few things:
1. We should not have tow identical `getOwnershipTypeDisplay` functions
2. The content/labels should come from `en.json` file

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://strr-ui-dev--pr-135-z1swt59e.web.app

**Comment by shaangill025** [comment]
> Few things:
> 
> 1. We should not have tow identical `getOwnershipTypeDisplay` functions
> 2. The content/labels should come from `en.json` file

@dimak1 Changes have been made.

**Review by dimak1 — APPROVED** [review]
LG! Thanks!

**Pull request merged**
