### PR TITLE
ui review fixes

### PR DESCRIPTION
**Pull request by turb0c0w**
*Issue:*https://github.com/bcgov/entity/issues/

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the namex license (Apache 2.0).

### CODE REVIEW

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://strr-ui-dev--pr-8-96f9qjij.web.app

**Review by trevoratindustrio — APPROVED** [review]

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://strr-ui-dev--pr-8-96f9qjij.web.app

**Pull request merged**
