### PR TITLE
Host UI - Only Allow PDF Document Upload

### PR DESCRIPTION
**Pull request by shaangill025**
*Issue:*

- https://github.com/bcgov/entity/issues/23014

*Description of changes:*
Only allow .pdf supporting document upload.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the namex license (Apache 2.0).

### CODE REVIEW

**Review by dimak1 — APPROVED** [review]

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://strr-ui-dev--pr-254-3s7iukdi.web.app

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://strr-ui-dev--pr-254-3s7iukdi.web.app

**Pull request merged**
