### PR TITLE
Form State Store

### PR DESCRIPTION
**Pull request by samIndustrio**
*Issue:* 
[20972](https://app.zenhub.com/workspaces/strr-65b2a7146835aa0cdf315b79/issues/gh/bcgov/entity/20972)
[20976](https://app.zenhub.com/workspaces/strr-65b2a7146835aa0cdf315b79/issues/gh/bcgov/entity/20976)
[20975](https://app.zenhub.com/workspaces/strr-65b2a7146835aa0cdf315b79/issues/gh/bcgov/entity/20975)

*Description of changes:*

Adding validation and form operation POST
Adding validation logic for step changing
Integrate SBC connect

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the namex license (Apache 2.0).

### CODE REVIEW

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://strr-ui-dev--pr-16-ejp0ercq.web.app

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://strr-ui-dev--pr-16-ejp0ercq.web.app

**Review by trevoratindustrio — APPROVED** [review]

**Pull request merged**
