### PR TITLE
Add Application Number to application

### PR DESCRIPTION
**Pull request by shaangill025**
*Issue:*
- https://github.com/bcgov/entity/issues/22636
- https://github.com/bcgov/entity/issues/22897

*Description of changes:*
Added `application_number` to application table, Added function in migration to add application_number to existing records.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the namex license (Apache 2.0).

### CODE REVIEW

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://strr-ui-dev--pr-142-7b8ts3pk.web.app

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://strr-ui-dev--pr-142-7b8ts3pk.web.app

**Review by dimak1 — APPROVED** [review]

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://strr-ui-dev--pr-142-7b8ts3pk.web.app

**Comment by shaangill025** [comment]
CodeCov is not currently working and according to Patrick Wei we can disregard that check for now.

**Pull request merged**
