### PR TITLE
Add Business Licence Expiry Date

### PR DESCRIPTION
**Pull request by dimak1**
*Issue:*

- bcgov/entity/issues/23551

*Description of changes:*
- Add dynamic Business Lic Exp Date to Step 2 
- Add validation (is required)
- Review page update

Screenshot 2024-10-16 at 15 33 06

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the namex license (Apache 2.0).

### CODE REVIEW

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://strr-ui-dev--pr-186-ffkt8sqh.web.app

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://strr-ui-dev--pr-186-ffkt8sqh.web.app

**Review by shaangill025 — APPROVED** [review]
LGTM

**Pull request merged**
