### PR TITLE
Platform e2e playwright test

### PR DESCRIPTION
**Pull request by deetz99**
*Issue:*

- bcgov/entity/issues/25050

*Description of changes:*
https://github.com/user-attachments/assets/7e00084e-ed67-4735-85cc-5a1f90574c01

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the namex license (Apache 2.0).

### CODE REVIEW

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://strr-platform-dev--pr-414-rfh9zig0.web.app

**Review by thorwolpert — APPROVED** [review]

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://strr-platform-dev--pr-414-rfh9zig0.web.app

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://strr-examiner-dev--pr-414-zpg1hgax.web.app

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://strr-examiner-dev--pr-414-zpg1hgax.web.app

**Pull request merged**
