### PR TITLE
Strata - UI: UAT

### PR DESCRIPTION
**Pull request by deetz99**
*Issue:*

- bcgov/entity/issues/24810
- bcgov/entity/issues/24748
- bcgov/entity/issues/24757
- bcgov/entity/issues/24790
- bcgov/entity/issues/24766

*Description of changes:*
- update info collection notice modal content for strata
- update unit number validation for strata
- update error modal text when submitting application
- remove alert on review step for strata + platforms
- update todos on dashboard to include payment due option

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the namex license (Apache 2.0).

### CODE REVIEW

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://strr-platform-dev--pr-371-waql8kg4.web.app

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://strr-platform-dev--pr-371-waql8kg4.web.app

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://strr-platform-dev--pr-371-waql8kg4.web.app

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://strr-strata-hotel-dev--pr-371-8i7gq4hb.web.app

**Review by kialj876 — APPROVED** [review]
Nice work, looks good to me 👍

**Pull request merged**
