### PR TITLE
TEST - DO NOT MERGE: libphonenumber library test

### PR DESCRIPTION
**Pull request by deetz99**
Test phone number library

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the namex license (Apache 2.0).

### CODE REVIEW

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://strr-platform-dev--pr-387-se6hp77e.web.app

**Review by kialj876 — COMMENTED** [review]
Hmm the validation seems to update / seems correct, but the formatting gets messed up for most other countries

**Comment by bcregistry-sre** [comment]
Temporary Url for review: https://strr-platform-dev--pr-387-se6hp77e.web.app

**Comment by deetz99** [comment]
Closing as not needed

**Pull request closed without merging**
